### ISSUE TITLE
Review `teal.slice` documentations before release

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#314]
### Summary
Related with insightsengineering/nestdevs-tasks#25
We want to perform `teal.slice` release to introduce the first milestone of the filter panel upgrade.

### Pre-req
* https://github.com/insightsengineering/teal.slice/issues/315

### Acceptance Criteria
* Review and test roxygen examples
* Review vignettes 
* Update NEWS
* Update README (if applicable)
* Review DESCRIPTION file (i.e. dependency versions, etc)

**Comment by chlebowa** [comment]
Example apps were added recently to illustrate the inner workings of `FilterState` and its children as well as `DFFilterStates`. Since then the api has changed, which was accompanied by making several methods private. `$format` has also changed. The example apps must be caught up to these changes, they may not even work properly now. This can be done on `filter_panel_refactor@main`.

**Comment by pawelru** [comment]
Hi @gogonzo @chlebowa can you please close it if it's finished?

**Comment by gogonzo** [comment]
Done
