### ISSUE TITLE
[Feature Request]: reproducible `teal_slices`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#329]
### Feature description

`teal_slice` object should have method read/write method for the reproducibility purpose. Optimally saved state should be the same as format.

**Comment by m7pr** [comment]
Hey, few ideas below `teal_slice` is just an S3 R list with an extra `class` attribute `attr(*, "class")= chr [1:2] "teal_slice" "list"` . Let's see the below example

```{R}
x <- filter_var(
  dataname = "data",
  varname = "var",
  choices = NULL,
  selected = NULL,
  keep_na = NULL,
  keep_inf = NULL,
  fixed = FALSE,
  locked = TRUE,
  disabled = FALSE
)
x
teal_slice
 $ dataname: data
 $ varname : var
 $ disabled: FALSE
 $ fixed   : FALSE
 $ locked  : TRUE
```
```{R}
str(x)
List of 10
 $ dataname: chr "data"
 $ varname : chr "var"
 $ choices : NULL
 $ multiple: NULL
 $ selected: NULL
 $ keep_na : NULL
 $ keep_inf: NULL
 $ disabled: logi FALSE
 $ fixed   : logi FALSE
 $ locked  : logi TRUE
 - attr(*, "class")= chr [1:2] "teal_slice" "list"
```
```{R}
cat(format(x, show_all = TRUE))
teal_slice
 $ dataname: data
 $ varname : var
 $ choices : NULL
 $ multiple: NULL
 $ selected: NULL
 $ keep_na : NULL
 $ keep_inf: NULL
 $ disabled: FALSE
 $ fixed   : FALSE
 $ locked  : TRUE
```

So basically this task is about convenient way of storing an R list. We could use `saveRDS/readRDS` or `save/load` functions to store this R object in compressed R-related formats (`.rds` or `.rda`). `.rda` format also stores the name of the object, which in this case is not that important so we could go with .rds.

Storing of the object could be extended with an information on an R session in which this object was created (as a new attr added to the object). As a convenient tool for future reporoducibility. I can imagine some objects were created in teal.slice version 0.13 but some users might want to load them in 0.14 which can assume the format of `teal_slice` might be different (e.g. `disabled` field was removed).

When having a session information attached to the object we can figure out if the object can be used in the environment in which it is tried to be read/loaded. We can either thrown a warning/error preventing this object to be used (based on a stored session and exisiting session information) or we can update the object on the fly - remove fields that are not needed and append fields that are missing with the default values of teal_slice object in the existing session. We do not need to know the R session information in which this object was created to update the object to the existing session in which it will be loaded, but this is a nice to have.

If we do not go with the storage of the R session as an attribute of stored teal_slice, we can go with different formats than `.rda`. We can store the object as a `JSON`, so that the structure is visible from the text editor and git commits. storing as JSON can have the same behavior on the mismatch of current `teal_slice` format that is required by the current R session and the time in which this object was stored. We can either raise the warning/error or we can silently update the object as I mentioned above.


To sum things up
1)
- we attach a new attribute to `teal_slice` on the storage so that it stores the R Session Information next to the object
- we store as `.rda`
- update: when object is loaded/restored to the current session we verify it it has the desired structured for the version of `teal.slice` that is used in the existing R session in which we are trying to load the object - and we update the object

2) 
- we do not attach R Session Information
- we store as `JSON`
- update - the same as in 1)

@gogonzo any preferences based on your experience with this package? Any other ideas that you envisioned?

**Comment by m7pr** [comment]
We had a small call to sort things up. Below is the summary of what we agreed

We considered YAML vs JSON. We decided to go for JSON format for now, as it stores vectors in one line and does not have issues reading unnamed lists.

The plan
- create `storage` function both for `teal_slice` and `teal_slices`
- for `teal_slices` we need to also store attributes that are passed to `filter_settings` by `exclude_varnames`, `include_varnames` and `count_type` parameters
- `print().teal_slice*` and `format().teal_slice*` should be S3 generic methods for `teal_slice` and `teal_slices` should use `storage` function, and only trim the result to specific number of lines for clean output in R session
- create `read` function that restores `teal_slice*` object and updates the fields to the current format of `teal.slice` package version

How to work
- create new branch from `filter_panel_refactor@main`
- edit only `teal_slice.R` file (print/format methods + create storage/read)
- do not edit tests
- merge to `135_multiple_filterpanels@filter_panel_refactor@main` branch
- decide if the behavior of `exclude_varnames`, `include_varnames` and `count_type` arguments of `filter_settings` should be changed so that they do not create attributes but they are a part of the output list
    - if yes, update storage/read
- update tests on `135_multiple_filterpanels@filter_panel_refactor@main` branch

**Comment by chlebowa** [comment]
> `print().teal_slice*` and `format().teal_slice*` should be S3 generic methods for `teal_slice` and `teal_slices` should use `storage` function, and only trim the result to specific number of lines for clean output in R session

Can you please clarify this? `teal_slices` should use `storage` for what? Printing?

Here are my initial thoughts:
1. I think JSON is the better option.
2. I'm not sure `teal_slice` objects need their own storage mechanism if all we ever pass around in `FilteredData` and `teal::init` are `teal_slices` objects but perhaps I am missing something. Maybe `teal_slice_expr` and integration with `citril` could benefit from this?
3. Changing `teal_slices` attributes to fields has the potential of wrecking subset and concatenating methods for this class. Proceed with caution.
4. Do we need the whole session information stored with a `teal_slices`? Would `teal.slice` version not suffice?
5. I understand that if a `teal_slices` is stored with a version (of whatever we decide) and is to be adapted to the user's session, the adaptation will be done by the `read` function or its internals. I believe comparing `teal_slice` content to `filter_var` formals is a good starting point for such adaptations.

Finally, on branch 135 `teal_slice` is no longer a list, which will complicate things, but only slightly.

**Comment by m7pr** [comment]
@chlebowa `print.teal_slice*()` s3 generic method will use `format.teal_slice*()` s3 generic method that will use `storage.teal_slice*()` s3 generic method. `storage()` will decompose R reactive list containing `teal_slice*` into JSON and `format()` will only reformat this JSON for printing.

**Comment by m7pr** [comment]
> Finally, on branch 135 teal_slice is no longer a list, which will complicate things, but only slightly.

Yeah, I am using the same workaround we now have in `format()`

```{R}
  x <- if (shiny::isRunning()) {
    rev(shiny::reactiveValuesToList(x))
  } else {
    rev(shiny::isolate(shiny::reactiveValuesToList(x)))
  }
```

**Comment by m7pr** [comment]
> Changing teal_slices attributes to fields has the potential of wrecking subset and concatenating methods for this class. Proceed with caution.

I think the same. attributes moved to fields could break a lot

**Comment by m7pr** [comment]
> Do we need the whole session information stored with a teal_slices? Would teal.slice version not suffice?
> I understand that if a teal_slices is stored with a version (of whatever we decide) and is to be adapted to the user's session, the adaptation will be done by the read function or its internals. I believe comparing teal_slice content to filter_var formals is a good starting point for such adaptations.

Yeah, honestly session information or version is not needed. We can use `formals()` to adapt the read object to the current requirements of the current version of the `teal.slice` package.

**Comment by m7pr** [comment]
Yes, `storage()` changes R reactive list to a JSON and stores it into a file. If it already creates some format of the object then we can reuse this format for `format()`ing and `print()`ing

**Comment by m7pr** [comment]
And this way you have the same format that is visible for the user in the session and in files with stored objects

**Comment by chlebowa** [comment]
But would you call a function that saves every time you want to print?

**Comment by m7pr** [comment]
No, it is parametrized : ) and if file parameter is empty then it returns the formatted to JSON object, so that it can be used in `format()`
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/a9a06c82-c824-4f28-9111-e17ef98745fd)

**Comment by chlebowa** [comment]
I hate this.
Let's talk about it tomorrow.

**Comment by m7pr** [comment]
Here is the current state of storage > format > print for JSON output for `teal_slice` so that we have an example for the discussion

```{R}
> filter_1 <- filter_var(
+   dataname = "dataname1",
+   varname = "varname1",
+   choices = letters[1:10],
+   selected = "b",
+   keep_na = TRUE,
+   fixed = FALSE,
+   extra1 = "extraone"
+ )
> store(filter_1)
{
  "dataname": "dataname1",
  "varname": "varname1",
  "choices": ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
  "selected": "b",
  "keep_na": true,
  "fixed": false,
  "locked": false,
  "multiple": true,
  "id": "dataname1 varname1",
  "extra1": "extraone"
} 
> format(filter_1)
[1] "teal_slice\n{\n  \"dataname\": \"dataname1\",\n  \"varname\" : \"varname1\",\n  \"choices\" : [\"a\", \"b\", \"c\", \"d\", \"e\",...\n  \"selected\": \"b\",\n  \"keep_na\" : true,\n  \"fixed\"   : false,\n  \"locked\"  : false,\n  \"multiple\": true,\n  \"id\"      : \"dataname1 varname1\",\n  \"extra1\"  : \"extraone\"\n} "
> print(filter_1)
teal_slice
{
  "dataname": "dataname1",
  "varname" : "varname1",
  "choices" : ["a", "b", "c", "d", "e",...
  "selected": "b",
  "keep_na" : true,
  "fixed"   : false,
  "locked"  : false,
  "multiple": true,
  "id"      : "dataname1 varname1",
  "extra1"  : "extraone"
} 
```

**Comment by m7pr** [comment]
A bit more clarification after the call that we had:

- format should use toList() function that recreates reactiveList to List
    - this should also pay attention to the order of the output
    - toJSON() is applied over an reordered toList() and digits=16 argument is passed for numeric values
- format should reshape the JSON output so it adds whitespace before colons and trails the output to specific length

- store should be a cat() of a an unreshaped format with show_all = TRUE
- print should be able to pass show_all to format so that format does not necessarily show everything right now
- only teal_slices has the ability to store as we do not plan to store teal_slice

There's gonna be a separate discussion about show_all/skip_default behavior for reporter module

**Comment by chlebowa** [comment]
Not exactly.
`teal_slices` is a list and `teal_slice` is a `reactiveValues`. The latter must be converted to a list before converting to JSON. For some reason (might be platform dependent) `shiny::reactiveValuesToList` may return the contents in a different order.
`toList` was meant as a convenience function for converting `teal_slices` to JSON but it is probably superfluous.
