### ISSUE TITLE
bug in adding filters

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.slice#346]
`filter_panel_refactor@main`

This error appears when filters are specified for all variables of a data set.

![image](https://github.com/insightsengineering/teal.slice/assets/114988527/0d8ccac1-a47b-45ba-ad73-58f68a0f396e)

**Comment by m7pr** [comment]
Hey @chlebowa on which moment (commit) of `filter_panel_refactor@main` branch you are working on? Can you check if this happens on few last states (commits) of the branch? 
https://github.com/insightsengineering/teal.slice/commits/filter_panel_refactor%40main

Can you check out to those commits, build the package and check if this error appears?
![image](https://github.com/insightsengineering/teal.slice/assets/133694481/eb45971d-c89b-462c-a022-5f68fd817a7f)

Lastly, what do you think about submitting bugs with an R session and an information of a commit on which you were when facing the bug, so that in the future it's easier to track bugs (+ motivate people to do more manual testing) and detect if they are outdated or not, and what was the cause of the issue. Thanks

**Comment by chlebowa** [comment]
I am working on
`teal.slice` 724dd0d8e9ce4dee76a3127af91b8dd5014e4227
`teal` ede832f13dba57d387fba6058d8060f6611ffeb2

I do not think I can check the older commits in `teal.slice` as now that brach 135 has been merged in `teal` apps with specified filters crash with 
```
Error in .subset2(x, "impl")$toList(all.names) : 
  attempt to apply non-function
```

**Comment by m7pr** [comment]
Oh yeah, that would require a cross check of commits in both packages to detect the exact moment and the cause of the crash. Thanks for the reply
