### ISSUE TITLE
Redesign the filter-panel (research)

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.slice#47]
Please provide the balsamic

**Comment by gogonzo** [comment]
Please consider following:
- possibly enable hierarchical filtering. Discuss how the dataset related filters should be changed when other filter is applied. For example imagine two filters SEX and AGE. If SEX filter is limited only to say `F`, how the AGE should be affected: 
    - AGE slider entire range should be limited to the values presented in the filtered-data?
    - AGE slider entire range should remain the same (as unfiltered data) but the selected range should be modified? What happens if user tries to extend this selected range? Can user select AGE range to outside of the filtered-data range but within unfiltered data range?
- Inclusion of the filter labels - should there be two unlabeled and labeled filter selections? What if user select labeled filter and unlabeled which involves the same variable
- global and local filters. Can user select global and local filter for the same variable?

**Comment by nikolas-burkoff** [comment]
So rather than thinking about general filtering I wonder if we should be understanding what types of filters are most useful and making the filter panel easier to use for those cases (for example some datasets/variables are much more important to filter on) - if as an app users you are not aware of all the details of all your datasets it can be daunting to set the filters you want.

So you could imagine a "subgroup filter" which allows users/app developers to specify a set of subjects based on some filters in say ADSL which filters the rest of the data accordingly - each of these subgroup filters is named and then in the filter panel you can easily turn on/off a subgroup filter

You could imagine a paramcd filter, an endpoint filter, a visit filter and maybe others which provide other intuitive ways of filtering the data - you then can of course have a completely general filter so more obscure cases can still be done. Certain modules (in say goshawk) which require say a paramcd filter could require an app developer to include one in their filters argument etc. 

When creating/editing/viewing details of these filters a modal is used and say for a paramcd filter the information/UI could be tailored to that type of filter and in the filter panel you see (maybe with a mouse over) some details and the different filter types could be coloured and easy to turn on and off. 

You could even have a mark on the filter which donates whether the filter is "turned on" for all modules or only the current one sort of handling whether the filter is (currently) global or not.

You could then imagine the (teal) reporter being able to do smarter things with the filters (i.e. defining a set of filters at the beginning of the report and then saying in the cards "Output for Subgroup XXX, for details see filter list"

The above of course would also need to work for MAE data and also require some analysis to work out what filters would most help the user base and is a big step away from here is a list of columns of your data to filter and so may not be feasible without a huge amount of effort.

**Comment by danielinteractive** [comment]
One important feature request that I hear from e.g. dashdis folks sometime is to allow for predefined filters. So would it be possible for teal to support a simplified filter panel as alternative option, so that the user does not need to select stuff from dropdown menus etc. but can just click on simple on/off buttons, to select efficacy population etc.

**Comment by Polkas** [comment]
KEYWORDS: SPECIALISM, SIMPLIFY, SHARED-ENGINE
Summing up we need to have a FIlter Panel factory (design pattern) which will provide different panels for specific scenarios.
Some of these panels will be highly simplified (@danielinteractive suggestion). From the code maintenance perspective it will be great to have as much as possible shared engine for all type of filter panel.

**Comment by kumamiao** [comment]
[A quick summary of current user requests here](https://docs.google.com/document/d/1lfRolkS2kL9noMndDJ3FvqT0yxk5lmrQTBQX0TjRAOc/edit?hl=en&forcehl=1#)

**Comment by gogonzo** [comment]
> [A quick summary of current user requests here](https://docs.google.com/document/d/1lfRolkS2kL9noMndDJ3FvqT0yxk5lmrQTBQX0TjRAOc/edit?hl=en&forcehl=1#)

From above document I conclude that we need couple of things which require consistent API for app-developer to set them up. I can distinguish so far 5 not-exclusive scenarios:

### 1. Option to specify initial filter states (available already)

```r
# I want to start the app with filters on: ADSL.gender{M, F} and ADRS.avisit{baseline, week 1}

filters = list(
  ADSL = list(
    gender = list(c("M", "F"))
  ),
  ADRS = list(
    baseline = list("week 1")
  )
)
```
### 2. Option to specify possible filterable variable choices (done [here](https://github.com/insightsengineering/teal/pull/724))

```r
# I want to limit filter variables to: adsl.{gender, age, sex, race, country, arm} and adrs.{avisit, paramcd, aval}

filters = list(
  ADSL = list(
    ...,
    filterable = c("gender", "age", "sex", "race", "country", "arm")
  )
)
```
### 3. Option to specify module-specific filters.

```r
# I want to add module-filter: adrs.paramcd{besrspi, invet}

filters = list(
  ADRS = list(
    paramcd = list(
      c("basrspi", "invet"), 
      modules = c("KM Plot", "Demographic table", ...)
  )
)
```

### 4. Option to create filter-labels which de facto are custom-filters loaded from file or specified manually.

```r
# I want to add custom-filter (including filter-flag):
 - adult-male: adsl.gender == m & adsl.age >= 18
 - adult-woman: adsl.gender == f & adsl.age >= 18
 - minor

filters = list(
  ADSL = list(
    genderage = custom_filter(
      label = "Gender and age category",
      `adult-male` = gender == "m" & age >= 18,
      `adult-woman` = gender == "f" & age >= 18,
      `minor` = age < 18
    )
  )
)
```

### 5. Option to specify fixed filter (for all modules or specific modules)

This one is problematic as `fixed` could mean.
```r
# I want gender filter to be fixed (not removable):

filters = list(
  ADSL = list(
    gender = list(c("M", "F"), fixed = TRUE)
  )
)
```

Another things to consider:
- do we need `multiple = TRUE/FALSE` argument to allow multiple or single selection
- what `fixed` could mean exactly. Filter which can't be changed and removed or can't be removed but can be changed.

**Comment by gogonzo** [comment]
WIP: I'll continue in this post with some UML focused on backend.

**Comment by kumamiao** [comment]
re: hierarchical filter, I think the issue is that currently in our filter panel, the filtering statistics (counts, ranges, etc.) cannot reflect the last filtered data, but only the original unfiltered data, which could be confusing and make it hard to fulfill some needs (i.e., to filter AVAL for based on certain PARAM in ADLB). The concept of the cascading/context filters sound good, will also take a look at some Spotfire examples.

> Any thoughts on how to get the filter information back to ADSL for filtering for subgroups? It sounds like that is quite an important piece of functionality ( @kumamiao ?) - even if it's not implemented now we should make sure it could be implemented in future?

User request is reasonable given the analysis scenarios (i.e., subgroups who have a certain AE [based on ADAE], subgroups who have abnormal glucose [based on ADLB], etc.) and is marked to be urgent, although I am also debating on the generalization vs. clinical use for this feature. My initial thought is when users apply filters for non-parent data, there will be a checkbox next to the data name, for users to choose whether to create a subgroup. If so, a new flag will be created in the parent data (user can fill in flag name and filter label via a pop-up window) if the the primary keys in the parent data also exist in the filtered non-parent data. Happy to hear other possibilities as well.

**Comment by npaszty** [comment]
@nikolas-burkoff 

the goshawk screening and baseline data constrain filtering is very specific. it allows users to filter out subjects who have baseline values, for example, between a specifically set range. this can't be done effectively with current filter design. if paramcd was filtered to let's say ALT then it would be very difficult if not impossible to filter base because the slider would include the range of all biomarkers.  so along the lines of what was noted above but with a much broader range.

no paramcd filtering
![image](https://user-images.githubusercontent.com/40777373/190528633-6a489495-1324-4b41-aff2-70169fcbd16e.png)

filtered to one paramcd and no change in base range. 
![image](https://user-images.githubusercontent.com/40777373/190529133-0e642283-b5bb-4fbc-b41c-e9bdfaa6bafb.png)

a much more simple concept is if you filter on gender "F" for a demographics subset then you don't want to see data in the filters that belong to "M". 
SAS viewtable creates hierachical filtering and to me that's what you would expect from a data filtering.

**Comment by npaszty** [comment]
had follow up discussion on dynamically building UI elements into the encoding panel. this could be done using a couple of additional arguments to the modules. one argument to indicate if dynamic UI element code should execute (logical) and the other being a list of lists instruction. list element would be type of ui and values. so list(radio, c("Ocular AESIs = aesi", "Ocular Serious AEs")), etc.

this would need to be implemented via a renderUI in the server function along with a code block to do the filtering of the reactive data. found this article on [dynamic UI elements in shiny](https://www.r-bloggers.com/2019/09/dynamic-ui-elements-in-shiny/amp/). not exact match but concept indicates this would work.

with that said a little bird told me...
the proper way to filter data is to enable filter label based filtering in the filter panel. For example if the filter label ITT stands for the filter (subset) operation ADSL$ITTFL == "Y" and AESER stands for ADAE$SERIOUSAE == "Y" then one could have a select box where the user can select different filter labels, e.g. ITT and AESER and the resulting subset expression would be ADSL$ITTFL == "Y" & ADAE$SERIOUSAE == "Y"
this would match the current SPA thinking of subsetting data

**Comment by donyunardi** [comment]
@kumamiao and I discussed how the slider should behave when ranges recalculated during hierarchical filtering activity. 

For example:
1. We have demographic data with AGE overall ranges from 1-50
1. User filters AGE and updates the filter slider range to 10(min)-20(max)
1. User makes other filter changes which affects the AGE overall ranges to 30-50. 
1. Ranges recalculated, but what would happen to slider on step 2 since the min/max is now out of range? 

For this scenario, we think it makes sense to reset the filter slider range. We also suggest that this could always the default behavior for ranges/slider related for recalculating ranges.

**Comment by donyunardi** [comment]
Linking https://github.com/insightsengineering/teal.slice/issues/102
We want to expose FilterStates object from teal.slice so that user can extend it in their own package.

**Comment by gogonzo** [comment]
> @kumamiao and I discussed how the slider should behave when ranges recalculated during hierarchical filtering activity.
> 
> For example:
> 
> 1. We have demographic data with AGE overall ranges from 1-50
> 2. User filters AGE and updates the filter slider range to 10(min)-20(max)
> 3. User makes other filter changes which affects the AGE overall ranges to 30-50.
> 4. Ranges recalculated, but what would happen to slider on step 2 since the min/max is now out of range?
> 
> For this scenario, we think it makes sense to reset the filter slider range. We also suggest that this could always the default behavior for ranges/slider related for recalculating ranges.

This would lead to recalculation of each active FilterState. Because each FilterState (selected) value will be updated it will cause data filtering n-times. It means that if we have 5 filters, changing one FS can trigger recalculation of the module 5 times. To sequential retriggering we can apply some caching comparison mechanism, but nothing is for free (cache will affect size of the app). This is why I suggested to update counts only (density chart in case of slider).

**Comment by pawelru** [comment]
> I think there's been talk recently @mhallal1 @pawelru about having the option for **much more** locked down filter panels as certain use cases may require this

Let's don't bring that up yet. This discussion is still very much up in the air. Don't want to introduce some another level of complexity now

**Comment by donyunardi** [comment]
Note from collaboration:
* They use frequency where we use density.
* The frequency got updated when filter is modified (add/edit/delete).
* The two-tone color for filtered data for filtered vs non-filtered.

**Comment by gogonzo** [comment]
# Concept

Currently fiilter panel works in the way depicted on the diagram below. Filters are added by the user or through the API by `add_filter_variable`. `FilterState` is created from the selected column of a data.frame and populated to the `ReactiveQueue`. Based on the changes in `ReactiveQueue` different filter-call is evaluated (and thus different filtered data). All `FilterState` in the `ReactiveQueue` are shared by all modules and imediately applied to them all.

New proposition is slighty different. `ReactivseQueue` where active filters are kept needs a mapping interface to match the slot (module) with it's filters. The mapping system enables that modules will be able to use different set of filters. Because of the new mapping system UX/UI, API need necessary changes which will affect significant code refactor (but not rewriting from scratch)

![filter-panel-Concept drawio](https://user-images.githubusercontent.com/6959016/203022847-535071c3-1a36-4854-b390-daa9e43d0d98.png)

Before going further, it's important to distinguish few terms:

1. Filterable - name of the columns in datasets which can be picked to create a filter.
1. Labeled or available filter - a single filter with reactive values and label stored in the filters container. Equivalent of the current FilterState class. 
1. Enabled filter - same as (2) but assigned to particular slot (module).


Filter types:
- interactive filter - equivalent of the current filter (by column)
- fixed filter - fixed condition which can't be changed by the app user.
- filter group - a collection of filters (interactive or fixed). Combines the informations of the components

# API
Comming soon...

# UX design 
I'd like to present the UX prototype (first iteration). The prototype focuses on the interaction with the filter cards, filter manager, changing labels, and adding a new filter. 

## 1. Filter cards

Please see (interactive wireframe)[https://drive.google.com/file/d/1jYjYZR6Yqtfv7ZzMfBMa2T5xYIwWmVL7/view?usp=sharing]. **Enabled filters** are displayed in the filter-panel as "non-interactive" cards presenting summary of applied labeled filters. Clicking "gear" icon (or card itself) will show the interactive control of the filter. One can change the selected values and assign the label to the filter. By default labels are following a selection, so that:
- for numeric/interger/date - `$varname: $min-$max`
- for factors/characters: `$varname: $choice[1], ..., $choice[n]` cut on some character limits.
When user assigns the value to the filter it no longer follows the selection.
Icon `x` on the filter-card removes the filter from the slot (module).

Default             |  Interactive 
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/6959016/203026598-d191c127-5c41-458b-b08f-84b63ba2bffe.png)  |  ![image](https://user-images.githubusercontent.com/6959016/203026532-76efc4da-2b75-442f-8e61-11a907d2b800.png)cters - 

## 2. Enable/disable filters

In the module one can apply or unapply filters. By clicking "plus" on the top of the filter-panel menu should show up where one can select/deselect **labeled filters** for this module. One can also disable filters for the current module by clicking switch on the bottom of the dropdown.


Default             |  Enable/disable filters
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/6959016/203026598-d191c127-5c41-458b-b08f-84b63ba2bffe.png)  | ![image](https://user-images.githubusercontent.com/6959016/203032009-904027e2-d7c7-4d84-95b1-a44d53f06b69.png)

# 3. Filter manager

Opened by clicking "gear" icon on the top of the filter-panel. New modal will pop up

# 3.1 Add filter

If you look on the list in "Enable/disable filters " (2), you might ask "Ok, how to apply filter outside of the list". To do this, app user has to first add a labeled filter from the filterable (column). There are two dropdowns, first to select a dataset and second to select a filter. In the second dropdown one can select multiple options. Selecting two values automatically create a group. Please see [the wireframe](https://drive.google.com/file/d/1fk1Vo7M69wyJTWCS3GJpgtoFxJfETCjQ/view?usp=sharing)


Default             |  Enable/disable filters
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/6959016/203035526-56eef408-54e5-495e-a7cc-59f047b49f74.png)  | ![image](https://user-images.githubusercontent.com/6959016/203032009-904027e2-d7c7-4d84-95b1-a44d53f06b69.png)


After clicking save filter is saved to the list of labeled filters and then can be applied to the model.

# 3.2 Edit filter

# 3.2.1 Edit filter column

Similar to the "Filter cards" (1), here one can also select values of the labeled filter, change the label. But also can change other properties of the filter like:
- "single value only" (equivalent of `multiple` in the `selectizeInput`)
- possible choices
- reset to default values
- apply to multiple modules (probably not needed if we have "filters map")

![image](https://user-images.githubusercontent.com/6959016/203038106-63cebdf0-bc2c-4466-85c3-da706a9d93bf.png)

# 3.2.2 Edit filter group

Similar to (3.2.1) but on a group level. One can change label and selected values the labeled group and additional properties of labeled components.

![image](https://user-images.githubusercontent.com/6959016/203038295-1ca91c2d-f477-4ed1-9c32-35568cc1c719.png)

# 3.3 Filter map

In progress. To have a control over the slot/filters map.

# Further notes
- @nikolas-burkoff rangeslider should have option to zoom in range to see more detailed histograms. This is important for vectors which have kurtic ("peaked") distribitions.
- choices/ranges should be initialized on "unfiltered" data, but the distribution should present the values from the filtered data

**Comment by danielinteractive** [comment]
@gogonzo looks very comprehensive!
but also quite complex. Does this proposal include a an optional "low-complexity" filter version, that the app developer can activate?

**Comment by gogonzo** [comment]
@danielinteractive many things can be controlled by the app developer when initializing FP. I'm happy to continue discussions especially regarding MAE objects

**Comment by asbates** [comment]
When setting which filters can be applied to which modules, I would consider an option to not allow a given filter to apply to certain modules. Let's say I as an app developer do _not_ want users to be able to apply the Age 20-60 filter for the demographic table module. Then I would like a way to specify that so users are prevented from applying the Age 20-60 filter to the demographic table.



![203038295-1ca91c2d-f477-4ed1-9c32-35568cc1c719](https://user-images.githubusercontent.com/36482959/203182817-97fe94b8-abe4-40a4-a4da-68ecf5220de1.png)

**Comment by gogonzo** [comment]
Thanks @asbates , good point. Result of such configuration could look like this. Where some filters will be disabled to apply them in the module

![image](https://user-images.githubusercontent.com/6959016/203260170-3aa03d17-ade8-4b4a-af38-b0daef61745e.png)

**Comment by gogonzo** [comment]
I'm moving discussions to the document [here](https://docs.google.com/document/d/1rxnqYsjTfgl7Ift2IpD4SXUlpo0bHc1ie15O0JGzUWk/edit#) 
Let's update this issue if we conclude on something because comments here can make this messy.

**Comment by gogonzo** [comment]
@donyunardi I'm happy to close this one ;)
