### ISSUE TITLE
teal.slice example apps testing

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.slice#526]
### Summary
We'll conduct a manual test on two example apps where we focus on the teal.slice features.

Please do this on two apps (dev version):
- [x] [exploratory](https://genentech.shinyapps.io/nest_exploratory_dev/) @kartikeyakirar 
- [x] [early-dev](https://genentech.shinyapps.io/nest_early-dev_dev/) @m7pr 
- [x] [RNA-seq](https://genentech.shinyapps.io/nest_rna-seq_dev/) @m7pr 

Please play around with the filtering capability and log issue if there's any finding.

**Comment by vedhav** [comment]
Blocked by https://github.com/insightsengineering/teal.modules.clinical/issues/918
Will re-deploy the apps once this is merged and teal.gallery apps start to work.

**Comment by vedhav** [comment]
RNA-seq and exploratory and ready to test. The deployment of early-dev has errors which I will fix on Monday morning.

**Comment by vedhav** [comment]
All these apps are re-deployed. There is a bug in longitudinal app. But I'm looking into it.

**Comment by m7pr** [comment]
checked `early-dev` with respect to filter panel functionalities

- [X] runs at all!
- [X] all tabs show filter panel
- [X] It is possible to hide and show the filter panel
- [X] You can hide and show `Active Filter Summary`, `Active Filter Variables` and `Add Filter Variables`
- [X] I was able to add a new filter for a new variable that is shared across multiple tabs (so filters in this app are not module specific)
- [X] counts for `ADRSSWIM` were decreased both for Observations and Cases where a filter for applied, influencing other datasets to be changed as well
- [X] selection of NO levels for a filter with character/factor variables properly resulted in 0 observations being shown
- [X] restore and rewind arrows works for changing filter state
- [X] the same as above for remove filter icon
- [X] you can remove one filter or all filters for a dataset
- [X] it is possible to have multiple filters set
- [X] DESELECT and SELECT ALL options forks for a character/factor with many levels
- [X] usage of continuous variable in a filter works as intended: tooltip is readable, label is visible, the column name is used, you can set limits manually in 2 cells or with dragging lines on a plot (rewind arrow also works, restore original state as well)
- [X] single counts in one filter gets reduced when another filter is set and values are limited as well
- [X] Global Filters information is shown
- [X] Snapshot Manager allows to: Add a Snapshot, Save to File, Upload a Snapshot, Revert to Original State
- [X] Downloaded Snapshot is properly represented in JSON structure
- [X] When a Snapshot is Uploaded, the `filters manager modal` gets closed automatically and the filter is applied
- [X] You can add or remove `Interactive Filters` in `Active Filters Variables` is you have snapshots created and uploaded, and also they are extended after each variable was used (so you can always quickly turn it on or off)
- [X] Plots and tables get updated when within a filter data is limited due to removal of a level in a character variable or due to the limitation of continuous variable


Regarding the testing of things not related to `teal.slice` 

- @vedhav I have found such an issue with Swimlane Plot. Would you be able to fix the app or diagnose which package caused that?
<img width="946" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/133694481/5aeca3ac-8f1b-45c3-8693-2f218a7e5fb5">

- @gogonzo the app view (plots, tables) get updated/refreshed if a new variable is added as a filter, even though it contains all levels by default at start. Do we need to update plots / tables if there is no change in the data (only a filter is added, but it is yet not used). Just to go `Variable Browser` module and `Add Filters Variable` that does not affect observation count in `Active Filter Summary` but the whole view gets refreshed.

**Comment by chlebowa** [comment]
https://github.com/insightsengineering/teal/issues/903

**Comment by m7pr** [comment]
Thanks @chlebowa - I do recall we talked about it before, but thought it's somehow resolved by now

**Comment by vedhav** [comment]
@m7pr Sure! I'll look into the Swimlane module issue.

**Comment by vedhav** [comment]
Turns out the actual bug was not module-specific and it was just because the app specified incorrect join_key parent-child mapping causing the filter panel to have wrong data.
I made this change in the teal.gallery please look at the PR https://github.com/insightsengineering/teal.gallery/pull/132
Also logged a feature request in `teal.slice` which we can handle later https://github.com/insightsengineering/teal.slice/issues/540

**Comment by m7pr** [comment]
RNA-seq testing:

# Checks

- [X] Filters for MAE datatype works as intended in early-dev

#Improvements

@vedhav is it possible to select `hd2` experiment as a default used on Forestplot? The current default one `hd1` has this message displayed
> No assays eligible for this experiment, please make sure to add normalized assays

# Questions

A question for @lcd2yyz and @gogonzo . On the Reporter prevewier view I know you were trying to use YAML-like display for selected variables. This way each variable and it's level is displayed in a new row. Do you think this is optimal for variables with more than 20 levels? Maybe for cases with multiple levels we could actually bind into one line. Check out how much scrolling is in this card
<img width="773" alt="image" src="https://github.com/insightsengineering/teal.slice/assets/133694481/a71d75cd-9a81-4f7a-a5bd-a9ef20cbc86e">

**Comment by donyunardi** [comment]
@m7pr 
It doesn't look ideal but then again, haven't heard any user feedback around this topic.
Let's make an issue so we can tackle and decide on this after the release.

**Comment by vedhav** [comment]
@m7pr Right now it is not possible to send the default experiment selection. I've created a [feature request](https://github.com/insightsengineering/teal.modules.hermes/issues/352) in tmh where this can be implemented. Thanks for pointing it out.

**Comment by donyunardi** [comment]
Issues opened. 
Thanks team!
