### ISSUE TITLE
[Feature Request]: Enable app developers to limit variables available in filter panel

### ISSUE THREAD

**Issue by kumamiao** [insightsengineering/teal.slice#70]
### Feature description

from @wangh107 

Provide a way for app developers to be able to limit filter panel variables choices to pre-specified variables. For example, I have an `ADSL` with 100 variables, as app developer, I wish to have a way to limit the available filtering variables to only allow some variables to be used as filters. i.e., I only want the app users to choose from `SEX`, `AGE`, `RACE`, `PDL1` as possible filters from `ADSL` on the filter panel.

```
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.
```

**Comment by nikolas-burkoff** [comment]
So at the moment in `teal::init` you specify default filters with the `filter` argument i.e.

```
data = cdisc_data(cdisc_dataset("ADSL", ...), cdisc_dataset("ADTTE", ...)),
modules = ...,
filter = list(
  ADSL = list(AGE = list(), SEX = ...),
  ADTTE = list(...)
)
```

If you do not care about specifying variables to be filtered then you leave unchange otherwise...

If you only want "AGE", "SEX" and "RACE" to be able to be filtered:

**Proposition 1**

```
data = cdisc_data(cdisc_dataset("ADSL", ...), cdisc_dataset("ADTTE", ...)),
modules = ...,
filter = list(
  ADSL = structure(list(AGE = list()), "filterable" = c("AGE", "SEX", "RACE")),
  ADTTE = list(...)
)
```

**Proposition 2**

```
data = cdisc_data(cdisc_dataset("ADSL", ..., filterable_variables = c("AGE", "SEX", "RACE"), cdisc_dataset("ADTTE", ...)),
modules = ...,
filter = list(
  ADSL = list(AGE = list()),
  ADTTE = list(...)
)
```

In either case this information needs to be passed to `[CDISC]FilteredData` - in prop 2 this would go through `init_filtered_data` and in prop 1 you would probably want a set filterable_varnames being called say [here](https://github.com/insightsengineering/teal/blob/main/R/module_tabs_with_filters.R#L155) 

I'm more tempted by prop2 as although it is a property of the data the information belongs with the filter information (and I really don't want to change teal.data for this. 

@insightsengineering/nest-core-dev opinions?

**Comment by Polkas** [comment]
I definitely prefer the Proposition 1 as the functionalities are better separated then.

**Comment by donyunardi** [comment]
I also think prop 1 is better because it categorizes the filter topic together.

**Comment by gogonzo** [comment]
I like proposition 1 but I think it's very similar to choices_selected and I wonder if we can try to standardise this across our packages. For example:
```
filters = list(
  ADSL = filter_spec(
    selected = list(SEX = value_choices(c("M", "F")),
    choices = variable_choices(c("SEX", "AGE", "RACE")
  )
)
```

Obviously, single item settings in the filter-panel are more complicated as they hhttps://github.com/insightsengineering/teal/pull/724ave also NA, Inf (which choices_selected doesn't handle) but I was thinking if we can unify this. The reason I'm rising this is that we have now two ways of specifying filters: 
1. `filterable` - limit number of possible filter-vars to and sets initial filter-var choice. Levels of each variable are not limited and not controllable.
2. `filter_spec` - limit number of possible filter-vars and sets initial filter-levels choices for each possible variable. Able to limit levels of each variable by `value_choices`

I guess we can continue with filterable and current teal.slice changes but I'd like to continue discussion on the filter-panel design discussions.

**Comment by nikolas-burkoff** [comment]
@gogonzo happy to merge in what we have - but also happy to pause this as we think about the best way of specifying things. The one thing I want to make sure we do is - if users want to allow all variables to be filterable (which I have to assume is the case almost always) - then it's **really easy** to do that
