### ISSUE TITLE
`get_code` unexpected behaviour

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.slice#94]
```
d1 <- data.frame(id = 1:5, pk = c(2, 3, 2, 1, 4), val = 1:5)
d2 <- data.frame(id = 1:5, value = 1:5)

cc <- teal.data:::CodeClass$new()
cc$set_code(c(
  "d1 <- data.frame(id = 1:5, pk = c(2,3,2,1,4), val = 1:5)",
  "d2 <- data.frame(id = 1:5, value = 1:5)"
))

fd <- teal.slice::init_filtered_data(
  x = list(
    d1 = list(dataset = d1, keys = "id"),
    d2 = list(dataset = d2, keys = "id")
  ),
  join_keys = teal.data::join_keys(teal.data::join_key("d1", "d2", c("pk" = "id"))),
  code = cc,
  check = TRUE
)
```

The code is stored correctly:

```
fd$.__enclos_env__$private$code$get_code()
```

But getting code doesn't work as `fd$get_code()` has default argument `dataname = self$datanames() => c("d1", d2")` but the code class only gives code if no datanames are given

![image](https://user-images.githubusercontent.com/15201933/187441329-72cae84c-349e-4850-85e7-8f8918850a38.png)

**Comment by donyunardi** [comment]
I feel that the problem may start from here:

https://github.com/insightsengineering/teal.data/blob/1d42d29ef36a2e5381ba2e233488c97eecde1027/R/CodeClass.R#L94-L105

```
    set_code = function(code, dataname = character(0), deps = character(0)) {
      checkmate::assert_character(code, min.len = 1, any.missing = FALSE)
      checkmate::assert_character(dataname, any.missing = FALSE)
      stopifnot(!(dataname %in% deps))


      code <- pretty_code_string(code)


      for (code_single in code) {
        private$set_code_single(code_single, dataname, deps)
      }
      logger::log_trace("CodeClass$set_code code set.")
      return(invisible(self))
```

If `CodeClass` initiated without `dataname`, then the default value is `character(0)`. 
Assertion won't kick in because `character(0)` is not a missing value.

If I add `dataname` when calling `cc$set_code()` method, the code works:

![image](https://user-images.githubusercontent.com/8597300/191671546-de2bdc32-dc2c-4085-945d-6e203dec92d3.png)

**Comment by donyunardi** [comment]
This issue is no longer relevant after we implemented with the new `teal_data` object.
Also, `init_filtered_data` is now deprecated.
